### PR TITLE
RRD Subscriber - NULL comparison

### PR DESCRIPTION
**Pull request by GrayTShirt**
There was an issue with creating rrd files after an update to the
subscriber. I did some testing and it looks like it we just need to put
some parenthesis in the logical comparison

### CODE REVIEW

**Comment by jhunt** [comment]
`==` binds tighter than `&&` (see http://en.cppreference.com/w/c/language/operator_precedence), so I'm not sure this change is warranted.

Can you reproduce the issue, and add a test case to `t/rrd-subscriber`?

**Comment by GrayTShirt** [comment]
So, I'm working on reproduction. It seems that with the CACHE logic, we generate CREATE pdus but we do not make it to the UPDATE pdu logic.

**Comment by GrayTShirt** [comment]
I really can't figure it out.

If I removed the rrdc_info logic to check for the rrd then it works, if I add the logic back in then the rrds stop updating.

**Comment by jhunt** [comment]
So you removed the parentheses, added tests, and force-pushed the commits to the branch?

**Pull request closed without merging**
