### PR TITLE
Store the metric type in the rrd map file

### PR DESCRIPTION
**Pull request by GrayTShirt**
I think I've updated to support the old style map, it should automatically update.

### CODE REVIEW

**Comment by jhunt** [comment]
Can you amend commit message to explain _why_ this is desirable?

Also, can you write a small test that verifies backwards-compatibility in reading older map files, and also asserts that they are transparently updated to the new format?

**Comment by GrayTShirt** [comment]
You're request is perfectly reasonable, but testing will probably take longer than I was hoping...

One of the problems I'v been having, is searching for datasource names, and one of the problems is samples and rates have different rrd ds names. Seeing that the map file is already used to find metrics, it seemed to be straight forward enough to add the metric type.

**Comment by jhunt** [comment]
Why is the test so complicated?

**Comment by GrayTShirt** [comment]
Commit comment updated, test added.

**Pull request merged**
