### PR TITLE
New bolo2redis subscriber

### LINKED ISSUE #24: New bolo2redis subscriber
Put all of the keys in a redis backend

### PR DESCRIPTION
**Pull request by filefrog**
Subscriber dutifully forwards all SET.KEYS key/value data to a single
redis host for storage.  This alleviates the core bolo from keeping
track of keys as state, and subsequent releases are now free to drop
that behavior.

Fixes #24

### CODE REVIEW

**Comment by filefrog** [comment]
@GrayTShirt, do you mind taking a look at this and letting me know what you think?

**Comment by GrayTShirt** [comment]
hey, could you fix the conflicts for this PR

**Comment by filefrog** [comment]
What conflicts?

**Comment by filefrog** [comment]
Merging by hand

**Pull request closed without merging**
