### PR TITLE
Update RPM building

### PR DESCRIPTION
**Pull request by GrayTShirt**
- move specfile into redhat/
- include new libraries
- path detection in bolo main (backwards compatibility)
- ABI versioning for new libraries

### CODE REVIEW

**Comment by jhunt** [comment]
Fair warning: lots of stuff will be changing over the next few weeks, so you may want to hold off on RPM packaging for now...

**Comment by GrayTShirt** [comment]
Okay, I figured the ABI versioning and the exe-path detection were useful though.

**Comment by jhunt** [comment]
... just wanted to make sure you weren't chasing the white whale on this one ...

**Comment by GrayTShirt** [comment]
yea, no worries, doing work like this helps me keep track of the project.

**Pull request merged**
